[project]
name = "rmrf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "rmscene",
    "rmc",
    "loguru>=0.7.2",
    "rich>=13.9.3",
    "pymupdf>=1.24.12",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
rmscene = { git = "https://github.com/ChenghaoMou/rmscene.git" }
rmc = { git = "https://github.com/ChenghaoMou/rmc.git" }
